### PR TITLE
Update naming of repo files from template

### LINKED ISSUE #1: Update repo with proper naming using the template repo
#### Description:

FYI @mchaf

### PR DESCRIPTION
**Pull request by michaelhoehn**
### Issues addressed by this PR

Closes #1

### CODE REVIEW

**Comment by michaelhoehn** [comment]
@BHoMBot check project-compliance

**Comment by michaelhoehn** [comment]
@BHoMBot check project-compliance

**Comment by michaelhoehn** [comment]
@BHoMBot fix project file ref. 9825267301

**Comment by michaelhoehn** [comment]
@BHoMBot check project-compliance

**Review by mchaf — APPROVED** [review]
Looks good to me. Only thing I would say is that 'SE 2050' has a space in it. Talking with MH though, i think it makes the most sense to keep it as SE2050_Toolkit.

**Pull request merged**
